-- SQL-файл для створення таблиць бази даних
-- АІС "Банк даних товарів, вироблених різними підприємствами"

CREATE TABLE IF NOT EXISTS product_groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS enterprises (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    statistical_code TEXT,
    city TEXT,
    address TEXT,
    phone TEXT,
    director_full_name TEXT,
    director_position TEXT,
    marketing_phone TEXT,
    marketing_head_full_name TEXT,
    contact_person TEXT
);

CREATE TABLE IF NOT EXISTS products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_number TEXT,
    name TEXT NOT NULL,
    group_id BIGINT REFERENCES product_groups(id)
);

CREATE TABLE IF NOT EXISTS enterprise_products (
    enterprise_id BIGINT REFERENCES enterprises(id),
    product_id BIGINT REFERENCES products(id),
    PRIMARY KEY (enterprise_id, product_id)
);

CREATE TABLE IF NOT EXISTS price_lists (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enterprise_id BIGINT REFERENCES enterprises(id),
    list_date DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS prices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    price_list_id BIGINT REFERENCES price_lists(id),
    product_id BIGINT REFERENCES products(id),
    price NUMERIC(10, 2) NOT NULL
);